name = "ParametricBT"
uuid = "558b9cde-5307-4f23-a62d-0d7c058ffbf2"
authors = ["Algopaul <72927083+Algopaul@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
